// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DescriptionPageTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void descriptionPage() {
    // Test name: DescriptionPage
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/");
    // 2 | setWindowSize | 1473x997 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1473, 997);
    // 3 | click | linkText=Sign In | 
    driver.FindElement(By.LinkText("Sign In")).Click();
    // 4 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 5 | type | name=email | pankajosplabs@gmail.com
    driver.FindElement(By.Name("email")).SendKeys("pankajosplabs@gmail.com");
    // 6 | type | name=password | Pankaj123
    driver.FindElement(By.Name("password")).SendKeys("Pankaj123");
    // 7 | click | css=label | 
    driver.FindElement(By.CssSelector("label")).Click();
    // 8 | click | name=rememberDetails | 
    driver.FindElement(By.Name("rememberDetails")).Click();
    // 9 | click | css=.fluid | 
    driver.FindElement(By.CssSelector(".fluid")).Click();
    // 10 | click | css=.button > .outline | 
    driver.FindElement(By.CssSelector(".button > .outline")).Click();
    // 11 | click | css=.teal:nth-child(3) | 
    driver.FindElement(By.CssSelector(".teal:nth-child(3)")).Click();
    // 12 | click | css=.ns-close | 
    driver.FindElement(By.CssSelector(".ns-close")).Click();
    // 13 | click | css=.button > .outline | 
    driver.FindElement(By.CssSelector(".button > .outline")).Click();
    // 14 | click | name=value | 
    driver.FindElement(By.Name("value")).Click();
    // 15 | type | name=value | Hi my name is Pankaj
    driver.FindElement(By.Name("value")).SendKeys("Hi my name is Pankaj");
    // 16 | click | css=.teal:nth-child(3) | 
    driver.FindElement(By.CssSelector(".teal:nth-child(3)")).Click();
    // 17 | click | css=.ns-close | 
    driver.FindElement(By.CssSelector(".ns-close")).Click();
    // 18 | click | css=.item:nth-child(4) > .ui | 
    driver.FindElement(By.CssSelector(".item:nth-child(4) > .ui")).Click();
  }
}
