// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LanguagePageTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void languagePage() {
    // Test name: LanguagePage
    // Step # | name | target | value
    // 1 | open | /Home | 
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/Home");
    // 2 | setWindowSize | 1473x997 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1473, 997);
    // 3 | click | linkText=Sign In | 
    driver.FindElement(By.LinkText("Sign In")).Click();
    // 4 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 5 | type | name=email | pankajosplabs@gmail.com
    driver.FindElement(By.Name("email")).SendKeys("pankajosplabs@gmail.com");
    // 6 | type | name=password | Pankaj123
    driver.FindElement(By.Name("password")).SendKeys("Pankaj123");
    // 7 | click | name=rememberDetails | 
    driver.FindElement(By.Name("rememberDetails")).Click();
    // 8 | click | css=.fluid | 
    driver.FindElement(By.CssSelector(".fluid")).Click();
    // 9 | click | linkText=Languages | 
    driver.FindElement(By.LinkText("Languages")).Click();
    // 10 | click | css=tbody:nth-child(2) .outline | 
    driver.FindElement(By.CssSelector("tbody:nth-child(2) .outline")).Click();
    // 11 | click | css=.fields > .five:nth-child(1) | 
    driver.FindElement(By.CssSelector(".fields > .five:nth-child(1)")).Click();
    // 12 | type | name=name | tdgefr
    driver.FindElement(By.Name("name")).SendKeys("tdgefr");
    // 13 | click | name=level | 
    driver.FindElement(By.Name("level")).Click();
    // 14 | select | name=level | label=Conversational
    {
      var dropdown = driver.FindElement(By.Name("level"));
      dropdown.FindElement(By.XPath("//option[. = 'Conversational']")).Click();
    }
    // 15 | click | name=level | 
    driver.FindElement(By.Name("level")).Click();
    // 16 | click | css=.buttons-wrapper > .teal | 
    driver.FindElement(By.CssSelector(".buttons-wrapper > .teal")).Click();
    // 17 | click | linkText=Languages | 
    driver.FindElement(By.LinkText("Languages")).Click();
    // 18 | click | css=tbody:nth-child(2) .remove | 
    driver.FindElement(By.CssSelector("tbody:nth-child(2) .remove")).Click();
    // 19 | click | css=.remove | 
    driver.FindElement(By.CssSelector(".remove")).Click();
  }
}
