// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LanguagePageTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void languagePage() {
    // Test name: LanguagePage
    // Step # | name | target | value
    // 1 | open | /Home | 
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/Home");
    // 2 | setWindowSize | 1473x997 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1473, 997);
    // 3 | click | linkText=Sign In | 
    driver.FindElement(By.LinkText("Sign In")).Click();
    // 4 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 5 | type | name=email | pankajosplabs@gmail.com
    driver.FindElement(By.Name("email")).SendKeys("pankajosplabs@gmail.com");
    // 6 | type | name=password | Pankaj123
    driver.FindElement(By.Name("password")).SendKeys("Pankaj123");
    // 7 | click | name=rememberDetails | 
    driver.FindElement(By.Name("rememberDetails")).Click();
    // 8 | click | css=.fluid | 
    driver.FindElement(By.CssSelector(".fluid")).Click();
    // 9 | click | linkText=Languages | 
    driver.FindElement(By.LinkText("Languages")).Click();
    // 10 | click | css=.ui:nth-child(2) > .row .ui .ui | 
    driver.FindElement(By.CssSelector(".ui:nth-child(2) > .row .ui .ui")).Click();
    // 11 | click | css=.six > .teal | 
    driver.FindElement(By.CssSelector(".six > .teal")).Click();
    // 12 | click | css=.ns-close | 
    driver.FindElement(By.CssSelector(".ns-close")).Click();
    // 13 | click | css=.item:nth-child(4) > .ui | 
    driver.FindElement(By.CssSelector(".item:nth-child(4) > .ui")).Click();
  }
}
