// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SkillTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void skill() {
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/Account/Profile");
    driver.Manage().Window.Size = new System.Drawing.Size(1473, 997);
    driver.FindElement(By.Name("email")).Click();
    driver.FindElement(By.Name("email")).SendKeys("pankajosplabs@gmail.com");
    driver.FindElement(By.Name("password")).SendKeys("Pankaj123");
    driver.FindElement(By.CssSelector(".field > .fluid")).Click();
    driver.FindElement(By.LinkText("Skills")).Click();
    driver.FindElement(By.CssSelector(".ui:nth-child(3) .ui .ui")).Click();
    driver.FindElement(By.Name("name")).Click();
    driver.FindElement(By.Name("name")).SendKeys("ABC");
    driver.FindElement(By.Name("level")).Click();
    {
      var dropdown = driver.FindElement(By.Name("level"));
      dropdown.FindElement(By.XPath("//option[. = 'Beginner']")).Click();
    }
    driver.FindElement(By.Name("level")).Click();
    driver.FindElement(By.CssSelector(".buttons-wrapper > .teal")).Click();
    driver.FindElement(By.CssSelector(".ns-box-inner")).Click();
    driver.FindElement(By.CssSelector(".ns-box-inner")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".ns-box-inner"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".ns-box-inner")).Click();
    driver.FindElement(By.CssSelector(".ns-box-inner")).Click();
    driver.FindElement(By.CssSelector(".ui:nth-child(3) .ui .ui")).Click();
    driver.FindElement(By.Name("name")).Click();
    driver.FindElement(By.Name("name")).SendKeys("SDE");
    driver.FindElement(By.Name("level")).Click();
    {
      var dropdown = driver.FindElement(By.Name("level"));
      dropdown.FindElement(By.XPath("//option[. = 'Intermediate']")).Click();
    }
    driver.FindElement(By.Name("level")).Click();
    driver.FindElement(By.CssSelector(".buttons-wrapper > .teal")).Click();
    driver.FindElement(By.CssSelector("tbody:nth-child(2) .outline")).Click();
    driver.FindElement(By.Name("name")).Click();
    driver.FindElement(By.Name("name")).Click();
    {
      var element = driver.FindElement(By.Name("name"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Name("name")).SendKeys("WED");
    driver.FindElement(By.CssSelector(".buttons-wrapper > .teal")).Click();
    driver.FindElement(By.CssSelector("tbody:nth-child(3) .remove")).Click();
    driver.FindElement(By.CssSelector(".item:nth-child(4) > .ui")).Click();
  }
}
