// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test() {
    // Test name: test
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/");
    // 2 | setWindowSize | 955x766 | 
    driver.Manage().Window.Size = new System.Drawing.Size(955, 766);
    // 3 | click | css=.active | 
    driver.FindElement(By.CssSelector(".active")).Click();
    // 4 | click | linkText=Go to Profile | 
    driver.FindElement(By.LinkText("Go to Profile")).Click();
    // 5 | click | linkText=Skills | 
    driver.FindElement(By.LinkText("Skills")).Click();
    // 6 | click | css=.ui:nth-child(3) .ui .ui | 
    driver.FindElement(By.CssSelector(".ui:nth-child(3) .ui .ui")).Click();
    // 7 | click | name=name | 
    driver.FindElement(By.Name("name")).Click();
    // 8 | type | name=name | q
    driver.FindElement(By.Name("name")).SendKeys("q");
    // 9 | click | name=level | 
    driver.FindElement(By.Name("level")).Click();
    // 10 | select | name=level | label=Beginner
    {
      var dropdown = driver.FindElement(By.Name("level"));
      dropdown.FindElement(By.XPath("//option[. = 'Beginner']")).Click();
    }
    // 11 | click | name=level | 
    driver.FindElement(By.Name("level")).Click();
    // 12 | click | css=.buttons-wrapper > .teal | 
    driver.FindElement(By.CssSelector(".buttons-wrapper > .teal")).Click();
  }
}
