// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ValidateTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void validate() {
    // Test name: validate
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("http://192.168.99.100:5000/");
    // 2 | setWindowSize | 1473x997 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1473, 997);
    // 3 | click | linkText=Sign In | 
    driver.FindElement(By.LinkText("Sign In")).Click();
    // 4 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 5 | type | name=email | pankajosplabs@gmail.com
    driver.FindElement(By.Name("email")).SendKeys("pankajosplabs@gmail.com");
    // 6 | type | name=password | Pankaj123
    driver.FindElement(By.Name("password")).SendKeys("Pankaj123");
    // 7 | click | name=rememberDetails | 
    driver.FindElement(By.Name("rememberDetails")).Click();
    // 8 | click | css=.fluid | 
    driver.FindElement(By.CssSelector(".fluid")).Click();
    // 9 | click | css=.eight:nth-child(3) | 
    driver.FindElement(By.CssSelector(".eight:nth-child(3)")).Click();
    // 10 | assertText | xpath=//span[contains(.,'Part Time')] | Part Time
    Assert.That(driver.FindElement(By.XPath("//span[contains(.,\'Part Time\')]")).Text, Is.EqualTo("Part Time"));
    // 11 | assertText | xpath=//span[contains(.,'More than 30hours a week')] | More than 30hours a week
    Assert.That(driver.FindElement(By.XPath("//span[contains(.,\'More than 30hours a week\')]")).Text, Is.EqualTo("More than 30hours a week"));
    // 12 | assertText | xpath=//span[contains(.,'More than $1000 per month')] | More than $1000 per month
    Assert.That(driver.FindElement(By.XPath("//span[contains(.,\'More than $1000 per month\')]")).Text, Is.EqualTo("More than $1000 per month"));
    // 13 | click | css=.item:nth-child(4) > .ui | 
    driver.FindElement(By.CssSelector(".item:nth-child(4) > .ui")).Click();
  }
}
